# Site settings
title: Marijuana Indicators in Denver
timestamp: July 2014
email: your-email@domain.com
description: "Basic visualizations of Denver Marijuana data."
baseurl: ""
url: "http://yourdomain.com"
share: "Share this."

about:
  label: "Last updated"
  description: "The information presented here is a representation of Open Data provided by the City and County of Denver."

# Footer settings
footer:
  image: "images/flag_tag.svg"
  alt: "Code for America"
  link: "http://codeforamerica.org/"

# Build settings
markdown: redcarpet
permalink: pretty

# Custom collections
collections:
- subsections