name: Marijuana Indicators in Denver
timestamp: June 2014
markdown: redcarpet
pygments: true
about:
  label: "Last updated"
  description: "The information presented here is a representation of Open Data provided by the City and County of Denver."